ALTER TABLE "empresas"
ADD COLUMN "formulaCalculoPrecios" TEXT NOT NULL DEFAULT 'precio',
ADD COLUMN "produccionTipoCosto" TEXT NOT NULL DEFAULT 'op',
ADD COLUMN "tipoManejoPrecios" TEXT NOT NULL DEFAULT 'incluido_iva',
ADD COLUMN "sumarCantidadFacturacion" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "sumarCantidadTpvOffline" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "sumarCantidadProforma" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "sumarCantidadEntrega" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "ivaPredeterminado" TEXT NOT NULL DEFAULT '15%',
ADD COLUMN "tipoCalculoCosto" TEXT NOT NULL DEFAULT 'Costo Ultima Compra',
ADD COLUMN "almacenPredeterminado" TEXT NOT NULL DEFAULT 'Almacen General',
ADD COLUMN "transferenciasConIngreso" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "permitirTransferenciaStock" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "actualizarPreciosUltCompra" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "permitirMultiplesTarifas" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "tarifaMultimedidas" TEXT NOT NULL DEFAULT 'Precio 1',
ADD COLUMN "etiquetaUrbano" TEXT NOT NULL DEFAULT '3',
ADD COLUMN "formatoPrecio" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN "formatoPrecioIva" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN "formatoSubtotales" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN "formatoValorIva" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN "formatoTotal" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN "formatoCosto" INTEGER NOT NULL DEFAULT 6,
ADD COLUMN "formatoCostoSubtotales" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN "formatoCostoTotal" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN "formatoCostoValorIva" INTEGER NOT NULL DEFAULT 4,
ADD COLUMN "formatoCantidad" INTEGER NOT NULL DEFAULT 1;
