ALTER TABLE "empresas"
ADD COLUMN "generaAsientosContables" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "tipoModificacionAsientos" TEXT NOT NULL DEFAULT 'eliminar',
ADD COLUMN "centrosCostos" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "productosSinIvaInventarioCodigo" TEXT NOT NULL DEFAULT '1.1.03.01.02',
ADD COLUMN "productosSinIvaInventarioNombre" TEXT NOT NULL DEFAULT 'Inventarios De Prod. Terminados Sin Iva',
ADD COLUMN "productosSinIvaVentasCodigo" TEXT NOT NULL DEFAULT '4.1.01.02',
ADD COLUMN "productosSinIvaVentasNombre" TEXT NOT NULL DEFAULT 'Ventas Bienes Sin Iva',
ADD COLUMN "productosSinIvaCostoCodigo" TEXT NOT NULL DEFAULT '5.1.01.01.02',
ADD COLUMN "productosSinIvaCostoNombre" TEXT NOT NULL DEFAULT 'Costo De Ventas Mercaderia Sin Iva',
ADD COLUMN "productosConIvaInventarioCodigo" TEXT NOT NULL DEFAULT '1.1.03.01.01',
ADD COLUMN "productosConIvaInventarioNombre" TEXT NOT NULL DEFAULT 'Inventarios De Prod. Terminados Con Iva',
ADD COLUMN "productosConIvaVentasCodigo" TEXT NOT NULL DEFAULT '4.1.01.01',
ADD COLUMN "productosConIvaVentasNombre" TEXT NOT NULL DEFAULT 'Ventas Bienes Con Iva',
ADD COLUMN "productosConIvaCostoCodigo" TEXT NOT NULL DEFAULT '5.1.01.01.01',
ADD COLUMN "productosConIvaCostoNombre" TEXT NOT NULL DEFAULT 'Costo De Ventas Mercaderia Con Iva',
ADD COLUMN "tipoContabilizacionIngresos" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "tipoContabilizacionSalidas" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "ccCajasCodigo" TEXT NOT NULL DEFAULT '1.1.01.01.01',
ADD COLUMN "ccCajasNombre" TEXT NOT NULL DEFAULT 'Caja General',
ADD COLUMN "ccBancosCodigo" TEXT NOT NULL DEFAULT '1.1.01.02.01',
ADD COLUMN "ccBancosNombre" TEXT NOT NULL DEFAULT 'Banco Pichincha',
ADD COLUMN "ccClientesCodigo" TEXT NOT NULL DEFAULT '1.1.02.05.01',
ADD COLUMN "ccClientesNombre" TEXT NOT NULL DEFAULT 'Clientes',
ADD COLUMN "ccProveedoresCodigo" TEXT NOT NULL DEFAULT '2.1.03.01.01',
ADD COLUMN "ccProveedoresNombre" TEXT NOT NULL DEFAULT 'Proveedores Locales',
ADD COLUMN "ccRecepcionesCodigo" TEXT NOT NULL DEFAULT '1.1.03.01.06',
ADD COLUMN "ccRecepcionesNombre" TEXT NOT NULL DEFAULT 'Inventario Transitorio Recepciones de Compras',
ADD COLUMN "ccIvaComprasCodigo" TEXT NOT NULL DEFAULT '1.1.05.01.01',
ADD COLUMN "ccIvaComprasNombre" TEXT NOT NULL DEFAULT 'Iva En Compras',
ADD COLUMN "ccIvaPresuntivoCodigo" TEXT NOT NULL DEFAULT '1.1.05.01.01',
ADD COLUMN "ccIvaPresuntivoNombre" TEXT NOT NULL DEFAULT 'Iva En Compras',
ADD COLUMN "ccIrPresuntivoCodigo" TEXT NOT NULL DEFAULT '1.1.05.01.01',
ADD COLUMN "ccIrPresuntivoNombre" TEXT NOT NULL DEFAULT 'Iva En Compras',
ADD COLUMN "ccIceComprasCodigo" TEXT NOT NULL DEFAULT '5.3.01.20.08',
ADD COLUMN "ccIceComprasNombre" TEXT NOT NULL DEFAULT 'Ga- Impuesto Consumos Especiales Ice',
ADD COLUMN "ccAsumeRetCodigo" TEXT NOT NULL DEFAULT '5.2.01.27.12',
ADD COLUMN "ccAsumeRetNombre" TEXT NOT NULL DEFAULT 'Gv - Gastos Retenciones Asumidas',
ADD COLUMN "ccIvaVentasCodigo" TEXT NOT NULL DEFAULT '2.1.07.01.02.01',
ADD COLUMN "ccIvaVentasNombre" TEXT NOT NULL DEFAULT 'Iva En Ventas O Servicios',
ADD COLUMN "ccIceVentasCodigo" TEXT NOT NULL DEFAULT '2.1.07.01.04.01',
ADD COLUMN "ccIceVentasNombre" TEXT NOT NULL DEFAULT 'ICE En Ventas',
ADD COLUMN "ccPropinaVentasCodigo" TEXT NOT NULL DEFAULT '2.1.09.02.99',
ADD COLUMN "ccPropinaVentasNombre" TEXT NOT NULL DEFAULT 'Otras Cuentas Por Pagar Propinas',
ADD COLUMN "ccInteresVentasCodigo" TEXT NOT NULL DEFAULT '4.2.01.99',
ADD COLUMN "ccInteresVentasNombre" TEXT NOT NULL DEFAULT 'Intereses Diferidos',
ADD COLUMN "tipoContabilizacionCajas" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "tipoContabilizacionBancos" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "tipoContabilizacionCompras" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "tipoContabilizacionVentas" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "cobrosAnticiposCodigo" TEXT NOT NULL DEFAULT '2.1.10.01.01',
ADD COLUMN "cobrosAnticiposNombre" TEXT NOT NULL DEFAULT 'Anticipo De Cliente Cobro Cartera',
ADD COLUMN "cobrosCruceCodigo" TEXT NOT NULL DEFAULT '1.1.02.05.04',
ADD COLUMN "cobrosCruceNombre" TEXT NOT NULL DEFAULT 'Transitoria Cruce Clientes (Siempre Cero)',
ADD COLUMN "cobrosRetAtrasadaCodigo" TEXT NOT NULL DEFAULT '1.1.02.05.01',
ADD COLUMN "cobrosRetAtrasadaNombre" TEXT NOT NULL DEFAULT 'Clientes',
ADD COLUMN "tipoContabilidadCobros" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "pagosAnticiposCodigo" TEXT NOT NULL DEFAULT '1.1.04.03.03',
ADD COLUMN "pagosAnticiposNombre" TEXT NOT NULL DEFAULT 'Anticipo Otros Proveedores',
ADD COLUMN "pagosCruceCodigo" TEXT NOT NULL DEFAULT '2.1.03.01.03',
ADD COLUMN "pagosCruceNombre" TEXT NOT NULL DEFAULT 'Transitoria Cruce Proveedores (Siempre Cero)',
ADD COLUMN "tipoContabilidadPagos" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "cajaTransitoriaCodigo" TEXT NOT NULL DEFAULT '1.1.01.01.05',
ADD COLUMN "cajaTransitoriaNombre" TEXT NOT NULL DEFAULT 'Transferencias Internas (Cero)',
ADD COLUMN "bancosTransitoriaCodigo" TEXT NOT NULL DEFAULT '1.1.01.01.05',
ADD COLUMN "bancosTransitoriaNombre" TEXT NOT NULL DEFAULT 'Transferencias Internas (Cero)',
ADD COLUMN "vouchersComisionCodigo" TEXT NOT NULL DEFAULT '5.2.01.27.04',
ADD COLUMN "vouchersComisionNombre" TEXT NOT NULL DEFAULT 'Gv - Comisiones Tarjetas De Credito',
ADD COLUMN "tipoContabilizacionDepositos" TEXT NOT NULL DEFAULT 'no_contabilizar',
ADD COLUMN "nominaSueldoBasico" TEXT NOT NULL DEFAULT '',
ADD COLUMN "tipoContabilidadNomina" TEXT NOT NULL DEFAULT 'departamentos';
